### ISSUE TITLE
Separation of services

### ISSUE THREAD

**Issue by etienne-napoleone** [tomochain/tomochain-governance#87]
As of good practice, a service doing backend job (updating the DB) would be preferably separated from the frontend application.
Is there any dependency between each others? Or can we safely run them in separate Dockers?
For now I will make them run together in the same container, but it could be a good improvement for the future.

**Comment by thanhson1085** [comment]
This requires MongoDB, Nginx, and Services NodeJS, so we should run in separated containers. See `docker-stack.yml` file.

**Comment by etienne-napoleone** [comment]
```
pm2 start -x ./services/crawl.js
pm2 start -x --no-daemon index.js
```
Yes, I checked the Dockerfile and it's entrypoint and we are running those two services with pm2. This is my inital question :)
But for now I'm keeping them together

**Comment by thanhson1085** [comment]
Yep, should keep it together, let improve later if needed
